RAC-836: add ge badge
akeneo/pim-helpcenter pull request #1000
Opened 2021-09-01 09:08 UTC by juliensnz

2021-09-01 09:22 UTC, pierrejolly approved these changes

2021-09-01 09:24 UTC, pierrejolly commented on src/article.handlebars
> +                        <p class="small"><em>Only available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a> & on Growth Edition</em></p>
🤯
It should be the opposite

2021-09-01 14:08 UTC, felix-couprie commented
Tested ✅:

![Screen Shot 2021-09-01 at 16 01 43](https://user-images.githubusercontent.com/63246412/131686093-05114eac-6633-400f-a6e6-557efebc93e4.png)

<img width="783" alt="Screen Shot 2021-09-01 at 15 19 40" src="https://user-images.githubusercontent.com/63246412/131686111-14b4bfe6-64e7-41a8-9f51-18f55553e6ac.png">

2021-09-01 14:17 UTC, felix-couprie requested changes

2021-09-01 14:17 UTC, felix-couprie commented on src/article.handlebars
> +                        <p class="small"><em>Only available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a> & on <a href="https://www.akeneo.com/akeneo-p
```suggestion
                        <p class="small"><em>Only available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a> & <a href="https://www.akeneo.com/akeneo-pim-growth-edition/">Growth Edition</a></em></p>
```

2021-09-01 14:18 UTC, felix-couprie requested changes

2021-09-01 14:18 UTC, felix-couprie commented on content/md/imports-exports/tailored-export.md
> +ge-only: true
```suggestion
ge-only: false
```

2021-09-01 14:18 UTC, felix-couprie commented on content/md/imports-exports/tailored-export.md
> +ge-only: true
(It's not available in GE for now)

2021-09-01 15:48 UTC, felix-couprie requested changes

2021-09-01 15:48 UTC, felix-couprie commented on src/article.handlebars
> +                        <p class="small"><em>Only available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a></em></p>
```suggestion
                        <p class="small"><em>Available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a> & <a href="https://www.akeneo.com/akeneo-pim-growth-edition/">Growth Edition</a></em></p>
                    {{else}}
                        <p class="small"><em>Available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a></em></p>
```

2021-09-01 15:50 UTC, felix-couprie commented on src/article.handlebars
> +                        <p class="small"><em>Only available in our <a href="https://www.akeneo.com/akeneo-pim/?source=akeneo-help">Entreprise Edition</a></em></p>
Feedback from the team to get rid of the "Only" as it's not a unique choice for the first one

2021-09-02 09:55 UTC, felix-couprie commented
Tests: ✅ OK

![Screen Shot 2021-09-02 at 11 52 53](https://user-images.githubusercontent.com/63246412/131823290-c2bd0bd6-73f5-4a63-ac99-eb3e6a15f548.png)

<img width="88" alt="Screen Shot 2021-09-02 at 11 54 28" src="https://user-images.githubusercontent.com/63246412/131823588-038b6c83-d2ae-4b6a-ba3a-59368fff32a6.png">

![Screen Shot 2021-09-02 at 11 52 53](https://user-images.githubusercontent.com/63246412/131823602-80dc8d28-95ac-4c14-a00c-47140013b333.png)

2021-09-02 09:57 UTC, felix-couprie approved these changes
Tests: ✅ OK

![Screen Shot 2021-09-02 at 11 52 53](https://user-images.githubusercontent.com/63246412/131823290-c2bd0bd6-73f5-4a63-ac99-eb3e6a15f548.png)

<img width="88" alt="Screen Shot 2021-09-02 at 11 54 28" src="https://user-images.githubusercontent.com/63246412/131823588-038b6c83-d2ae-4b6a-ba3a-59368fff32a6.png">

![Screen Shot 2021-09-02 at 11 53 42](https://user-images.githubusercontent.com/63246412/131823684-4463f783-add9-488f-9f5d-4990d5bc65e2.png)

2021-09-02 10:01 UTC, merged