Modifying v6 version of the table attribute as Reference entity & mea…
akeneo/pim-helpcenter pull request #1149
Opened 2022-07-20 08:07 UTC by cbelval

…surement are not available columns in v6 compared to Serenity

2022-07-20 08:31 UTC, alexandrelissowski requested changes
remove the S at the begining of your doc. Otherwise, everything seems well.

2022-07-20 08:31 UTC, alexandrelissowski commented on content/md/first-steps/manage-multidimensional-data-in-a-table.md
> +s
you forgot this from your tests.

2022-07-20 13:29 UTC, cbelval commented on content/md/first-steps/manage-multidimensional-data-in-a-table.md
> +s
Thanks!

2022-07-21 08:53 UTC, pierallard approved these changes

2022-07-21 12:27 UTC, alexandrelissowski approved these changes

2022-07-21 12:34 UTC, merged