Update category ACLs for EC Early Access
akeneo/pim-helpcenter pull request #1263
Opened 2023-02-08 14:39 UTC by AurelieThirouard

As we will soon deliver EC Early Access in SaaS only (not v7), I need to update and add new specific ACLs to the article named "Manage the interface and actions accesses" in the  Permissions on categories section.  The merge will be only done after Master production branch is unfrozen and feature flag activated to release the feature.

2023-02-08 14:48 UTC, BryanS29-akeneo approved these changes

2023-02-09 09:41 UTC, alexandrelissowski requested changes
![Screenshot 2023-02-09 at 10-40-35 Manage the interface and actions accesses](https://user-images.githubusercontent.com/54275025/217775713-6098f2fe-7bad-45e7-81cd-d69dfc439f66.png)
Please check how to fix the layout.

2023-02-09 09:41 UTC, alexandrelissowski commented on content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
> + |
Line break inserted, the final layout is not good.

2023-02-09 09:41 UTC, alexandrelissowski commented on content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
> + |
Same, a line break introduces a new line.

2023-02-09 09:41 UTC, alexandrelissowski commented on content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
> +| Edit category attributes | Once a category template has been activated for a given category tree, user can access the edition of the category attributes through the `Attributes` tab of any of its c
```suggestion
| Edit category attributes | Once a category template has been activated for a given category tree, user can access the edition of the category attributes through the `Attributes` tab of any of its categories, at the condition that Edit categories has been activated. 
::: info
If you already have the right of Edit a category, the new Edit category attributes right will be automatically activated.
::: |
```
This is just a suggestion, I don't know if warning and info are working in tables.

2023-02-09 09:41 UTC, alexandrelissowski commented on content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
> +| Manage category permissions _(EE only)_ | User can access the `Permissions` tab on a category, at the condition that Edit a category right has been activated. User can handle which user groups are
Same, maybe try the Info callout with 'info :::'

2023-02-09 16:13 UTC, alexandrelissowski approved these changes

2023-02-15 16:32 UTC, merged